# Generated by Django 3.0.6 on 2020-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wordprocessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commdisaster',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=19, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=2)),
                ('grade', models.CharField(max_length=3)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('reportingunit', models.CharField(db_column='reportingUnit', max_length=50)),
            ],
            options={
                'db_table': 'commdisaster',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SelfIndo',
        ),
    ]
