# Generated by Django 3.0.6 on 2020-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civilstructure',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=19, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('basicallyintactsquare', models.CharField(db_column='basicallyIntactSquare', max_length=6)),
                ('damagedsquare', models.CharField(db_column='damagedSquare', max_length=6)),
                ('distoryedsquare', models.CharField(db_column='distoryedSquare', max_length=6)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('reportingunit', models.CharField(db_column='reportingUnit', max_length=50)),
            ],
            options={
                'db_table': 'CivilStructure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collapserecord',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=19, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=3)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('reportingunit', models.CharField(db_column='reportingUnit', max_length=50)),
            ],
            options={
                'db_table': 'CollapseRecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commdisaster',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=19, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=2)),
                ('grade', models.CharField(max_length=3)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('reportingunit', models.CharField(db_column='reportingUnit', max_length=50)),
            ],
            options={
                'db_table': 'commdisaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deathstatistics',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=19, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=5)),
                ('reportingunit', models.CharField(db_column='reportingUnit', max_length=50)),
            ],
            options={
                'db_table': 'DeathStatistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disasterprediction',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=19, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('depth', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('intensity', models.CharField(max_length=6)),
                ('type', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=3)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('reportingunit', models.CharField(db_column='reportingUnit', max_length=50)),
            ],
            options={
                'db_table': 'DisasterPrediction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disasterrequest',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=19, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('disastertype', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=1)),
                ('o_url', models.CharField(blank=True, db_column='o_URL', max_length=200, null=True)),
                ('reportingunit', models.CharField(db_column='reportingUnit', max_length=50)),
            ],
            options={
                'db_table': 'DisasterRequest',
                'managed': False,
            },
        ),
    ]
