# Generated by Django 3.0.6 on 2020-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=2, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=3, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'community',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=2, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'county',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=2, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=3, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'street',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
